#!/bin/sh

# chkconfig: 2345 93 25
# description: Starts and stops the RHQ agent
#
# processname: java
# pidfile: /var/run/jon-agent.pid

[ -f /etc/sysconfig/jon-agent ] && . /etc/sysconfig/jon-agent

export RHQ_AGENT_JAVA_HOME=/usr/lib/jvm/jre-1.6.0/

if [ "$2" = "--update" ]; then
  # we want to clear RHQ Admin configuration
  RHQ_AGENT_CMDLINE_OPTS="--daemon --cleanconfig"
fi

. $RHQ_AGENT_HOME/bin/rhq-agent-wrapper.sh